services:
  - type: web
    name: prepgrid-backend
    runtime: docker
    region: singapore
    plan: free
    rootDir: backend
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_URL
        value: https://prepgrid-1-9bl2.onrender.com
      - key: CLIENT_URL
        value: https://prepgrid-pold.vercel.app
      - key: GOOGLE_REDIRECT_URI
        value: https://prepgrid-1-9bl2.onrender.com/api/auth/google/callback
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama3-8b-8192
      - key: PISTON_URL
        value: https://emkc.org/api/v2/piston
      - key: MAIL_HOST
        sync: false
      - key: MAIL_PORT
        sync: false
      - key: MAIL_USER
        sync: false
      - key: MAIL_PASS
        sync: false
      - key: MAIL_FROM
        sync: false
